"""Change User.id to String

Revision ID: 75134c8b3de9
Revises: 
Create Date: 2026-01-15 12:55:58.891736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75134c8b3de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
